version: '3'
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    networks:
      - net
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    env_file:
      - .env
    networks:
      - net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - net
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 3


networks:
  net:
    driver: bridge
volumes:
  postgres:
    driver: local